apiVersion: apps/v1
kind: Deployment
metadata:
  name: twc-filter-stream-app
spec:
  selector:
    matchLabels:
      app: kafka-stream
  template:
    metadata:
      labels:
        app: kafka-stream
    spec:
      imagePullSecrets:
        - name: iot-pull-secret
      containers:
      - name: kafka-stream
        image: registry.iot.fh-joanneum.at/twc-filter-stream-app-latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"

